name: API workflow

on:
  push:
    branches: [main]

jobs:
  build:
check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16, 18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn
      - name: Run coverage tests
        run: yarn coverage
      - name: Upload coverage reports to Codecov
        run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov